"""refina modelo de turnos para 5 slots

Revision ID: 298729a06007
Revises: ad1175f8bd3a
Create Date: 2026-08-06 14:04:39.645129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298729a06007'
down_revision: Union[str, Sequence[str], None] = 'ad1175f8bd3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABELAS_COM_TURNO = (
    "instrutor_turno",
    "turmas_em_andamento",
    "turmas_sugeridas",
    "turma_sugerida_encontro",
)


def upgrade() -> None:
    """Upgrade schema."""
    # Remapeia os 3 valores antigos de turno para os novos 5 slots.
    # manha->manha_1 e tarde->tarde_1 são um mapeamento best-effort: o modelo
    # antigo nunca distinguia qual dos dois slots (1 ou 2) era realmente
    # usado — a equipe deve revisar manualmente os instrutores após a
    # migração. noite permanece inalterado.
    for tabela in TABELAS_COM_TURNO:
        op.execute(f"UPDATE {tabela} SET turno = 'manha_1' WHERE turno = 'manha'")
        op.execute(f"UPDATE {tabela} SET turno = 'tarde_1' WHERE turno = 'tarde'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrutor_turno', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_instrutor_turno_carga_positiva'), type_='check')
        batch_op.drop_column('carga_horaria_horas')

    with op.batch_alter_table('resultado_kpis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slots_disponiveis_total', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('slots_reposicao_sexta', sa.Integer(), nullable=False, server_default='0'))
        batch_op.drop_column('horas_disponiveis_total')
        batch_op.drop_column('horas_reposicao_sexta')

    with op.batch_alter_table('snapshot_capacidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slots_disponiveis', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('slots_ocupados', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('primeira_data_livre_por_slot_json', sa.Text(), nullable=False, server_default='{}'))
        batch_op.drop_column('horas_alocadas')
        batch_op.drop_column('horas_disponiveis')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Reversão best-effort e com perda de informação: dois slots (ex. manha_1 e
    manha_2) colapsam de volta em um único turno (manha), e os valores de
    carga horária/horas voltam com um placeholder (0), já que não há como
    reconstruir horas a partir de uma contagem binária de slots.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot_capacidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horas_disponiveis', sa.FLOAT(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('horas_alocadas', sa.FLOAT(), nullable=False, server_default='0'))
        batch_op.drop_column('primeira_data_livre_por_slot_json')
        batch_op.drop_column('slots_ocupados')
        batch_op.drop_column('slots_disponiveis')

    with op.batch_alter_table('resultado_kpis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horas_reposicao_sexta', sa.FLOAT(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('horas_disponiveis_total', sa.FLOAT(), nullable=False, server_default='0'))
        batch_op.drop_column('slots_reposicao_sexta')
        batch_op.drop_column('slots_disponiveis_total')

    with op.batch_alter_table('instrutor_turno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carga_horaria_horas', sa.FLOAT(), nullable=False, server_default='4'))
        batch_op.create_check_constraint(batch_op.f('ck_instrutor_turno_carga_positiva'), 'carga_horaria_horas > 0')

    # ### end Alembic commands ###

    # instrutor_turno tem UniqueConstraint(instrutor_id, turno) — um instrutor
    # com manha_1 E manha_2 geraria duas linhas colidindo em "manha" depois do
    # collapse. Remove o duplicado (mantendo a linha de menor id) antes de
    # colapsar os valores.
    op.execute(
        "DELETE FROM instrutor_turno WHERE id NOT IN ("
        "  SELECT MIN(id) FROM instrutor_turno GROUP BY instrutor_id,"
        "  CASE WHEN turno IN ('manha_1', 'manha_2') THEN 'manha'"
        "       WHEN turno IN ('tarde_1', 'tarde_2') THEN 'tarde'"
        "       ELSE turno END"
        ")"
    )
    for tabela in TABELAS_COM_TURNO:
        op.execute(f"UPDATE {tabela} SET turno = 'manha' WHERE turno IN ('manha_1', 'manha_2')")
        op.execute(f"UPDATE {tabela} SET turno = 'tarde' WHERE turno IN ('tarde_1', 'tarde_2')")
