"""adiciona tabela de oportunidades da simulacao

Revision ID: ad1175f8bd3a
Revises: d5c82375ef1c
Create Date: 2026-08-05 20:47:47.871291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1175f8bd3a'
down_revision: Union[str, Sequence[str], None] = 'd5c82375ef1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oportunidades_simulacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacao_id', sa.Integer(), nullable=False),
    sa.Column('tipologia_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('total_turmas', sa.Integer(), nullable=False),
    sa.Column('instrutor_ids_csv', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['simulacao_id'], ['simulacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipologia_id'], ['tipologias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oportunidades_simulacao', schema=None) as batch_op:
        batch_op.create_index('ix_oportunidade_sim_tipologia_data', ['simulacao_id', 'tipologia_id', 'data_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_oportunidades_simulacao_simulacao_id'), ['simulacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oportunidades_simulacao_tipologia_id'), ['tipologia_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidades_simulacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oportunidades_simulacao_tipologia_id'))
        batch_op.drop_index(batch_op.f('ix_oportunidades_simulacao_simulacao_id'))
        batch_op.drop_index('ix_oportunidade_sim_tipologia_data')

    op.drop_table('oportunidades_simulacao')
    # ### end Alembic commands ###
