"""esquema inicial

Revision ID: b136564f2f5d
Revises: 
Create Date: 2026-08-05 16:49:47.318204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b136564f2f5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('parametros_json_path', sa.String(length=500), nullable=False),
    sa.Column('periodo_de', sa.Date(), nullable=False),
    sa.Column('periodo_ate', sa.Date(), nullable=False),
    sa.Column('permitir_compartilhamento', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('periodo_ate >= periodo_de', name='ck_cenario_periodo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projetos_nome'), ['nome'], unique=True)

    op.create_table('tipologias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('carga_horaria_total_horas', sa.Integer(), nullable=True),
    sa.Column('horas_por_encontro', sa.Float(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('carga_horaria_total_horas IS NULL OR (carga_horaria_total_horas >= 24 AND carga_horaria_total_horas <= 60)', name='ck_tipologia_carga_total_faixa'),
    sa.CheckConstraint('horas_por_encontro IS NULL OR horas_por_encontro > 0', name='ck_tipologia_horas_encontro_positivo'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tipologias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipologias_nome'), ['nome'], unique=True)

    op.create_table('cenario_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cenario_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cenario_id'], ['cenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cenario_id', 'projeto_id', name='uq_cenario_projeto')
    )
    with op.batch_alter_table('cenario_projeto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cenario_projeto_cenario_id'), ['cenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cenario_projeto_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('datas_nao_letivas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.Enum('feriado', 'recesso', 'ferias', name='tipodatanaoletiva', native_enum=False, length=32), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('data_fim >= data_inicio', name='ck_data_nao_letiva_intervalo'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datas_nao_letivas', schema=None) as batch_op:
        batch_op.create_index('ix_data_nao_letiva_intervalo', ['data_inicio', 'data_fim'], unique=False)
        batch_op.create_index(batch_op.f('ix_datas_nao_letivas_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('instrutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrutores_nome'), ['nome'], unique=True)
        batch_op.create_index(batch_op.f('ix_instrutores_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('simulacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cenario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'executando', 'concluida', 'erro', name='statussimulacao', native_enum=False, length=32), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('tempo_execucao_seg', sa.Float(), nullable=True),
    sa.Column('solver_status', sa.String(length=50), nullable=True),
    sa.Column('objetivo_valor', sa.Float(), nullable=True),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.Column('log_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cenario_id'], ['cenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulacoes', schema=None) as batch_op:
        batch_op.create_index('ix_simulacao_cenario_iniciado', ['cenario_id', 'iniciado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulacoes_cenario_id'), ['cenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulacoes_status'), ['status'], unique=False)

    op.create_table('instrutor_dia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.CheckConstraint('dia_semana >= 2 AND dia_semana <= 6', name='ck_instrutor_dia_faixa'),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrutor_id', 'dia_semana', name='uq_instrutor_dia')
    )
    with op.batch_alter_table('instrutor_dia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrutor_dia_instrutor_id'), ['instrutor_id'], unique=False)

    op.create_table('instrutor_tipologia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('tipologia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipologia_id'], ['tipologias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrutor_id', 'tipologia_id', name='uq_instrutor_tipologia')
    )
    with op.batch_alter_table('instrutor_tipologia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrutor_tipologia_instrutor_id'), ['instrutor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instrutor_tipologia_tipologia_id'), ['tipologia_id'], unique=False)

    op.create_table('instrutor_turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.Enum('manha', 'tarde', 'noite', name='turno', native_enum=False, length=32), nullable=False),
    sa.Column('carga_horaria_horas', sa.Float(), nullable=False),
    sa.CheckConstraint('carga_horaria_horas > 0', name='ck_instrutor_turno_carga_positiva'),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrutor_id', 'turno', name='uq_instrutor_turno')
    )
    with op.batch_alter_table('instrutor_turno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrutor_turno_instrutor_id'), ['instrutor_id'], unique=False)

    op.create_table('resultado_kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacao_id', sa.Integer(), nullable=False),
    sa.Column('total_turmas_sugeridas', sa.Integer(), nullable=False),
    sa.Column('horas_formacao_total', sa.Float(), nullable=False),
    sa.Column('horas_disponiveis_total', sa.Float(), nullable=False),
    sa.Column('pct_ociosidade', sa.Float(), nullable=False),
    sa.Column('indice_balanceamento_carga', sa.Float(), nullable=False),
    sa.Column('indice_balanceamento_tipologia', sa.Float(), nullable=False),
    sa.Column('horas_reposicao_sexta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['simulacao_id'], ['simulacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resultado_kpis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resultado_kpis_simulacao_id'), ['simulacao_id'], unique=True)

    op.create_table('snapshot_capacidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacao_id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('horas_disponiveis', sa.Float(), nullable=False),
    sa.Column('horas_alocadas', sa.Float(), nullable=False),
    sa.Column('primeira_data_livre', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulacao_id'], ['simulacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulacao_id', 'instrutor_id', name='uq_snapshot_simulacao_instrutor')
    )
    with op.batch_alter_table('snapshot_capacidade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_capacidade_instrutor_id'), ['instrutor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshot_capacidade_simulacao_id'), ['simulacao_id'], unique=False)

    op.create_table('turmas_em_andamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_turma', sa.String(length=100), nullable=True),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('tipologia_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.Enum('regular_seg_qua', 'regular_ter_qui', 'intensiva_seg_qui', name='modalidade', native_enum=False, length=32), nullable=False),
    sa.Column('turno', sa.Enum('manha', 'tarde', 'noite', name='turno', native_enum=False, length=32), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim_prevista', sa.Date(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('data_fim_prevista >= data_inicio', name='ck_turma_andamento_datas'),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipologia_id'], ['tipologias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turmas_em_andamento', schema=None) as batch_op:
        batch_op.create_index('ix_turma_andamento_periodo', ['data_inicio', 'data_fim_prevista'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_em_andamento_instrutor_id'), ['instrutor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_em_andamento_projeto_id'), ['projeto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_em_andamento_tipologia_id'), ['tipologia_id'], unique=False)

    op.create_table('turmas_sugeridas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacao_id', sa.Integer(), nullable=False),
    sa.Column('tipologia_id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.Enum('regular_seg_qua', 'regular_ter_qui', 'intensiva_seg_qui', name='modalidade', native_enum=False, length=32), nullable=False),
    sa.Column('turno', sa.Enum('manha', 'tarde', 'noite', name='turno', native_enum=False, length=32), nullable=False),
    sa.Column('semana_inicio', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('num_encontros', sa.Integer(), nullable=False),
    sa.Column('carga_horaria_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['simulacao_id'], ['simulacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipologia_id'], ['tipologias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turmas_sugeridas', schema=None) as batch_op:
        batch_op.create_index('ix_turma_sugerida_sim_inicio', ['simulacao_id', 'data_inicio'], unique=False)
        batch_op.create_index('ix_turma_sugerida_sim_tipologia', ['simulacao_id', 'tipologia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_sugeridas_instrutor_id'), ['instrutor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_sugeridas_projeto_id'), ['projeto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_sugeridas_simulacao_id'), ['simulacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_sugeridas_tipologia_id'), ['tipologia_id'], unique=False)

    op.create_table('turma_sugerida_encontro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_sugerida_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('turno', sa.Enum('manha', 'tarde', 'noite', name='turno', native_enum=False, length=32), nullable=False),
    sa.Column('horas', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['turma_sugerida_id'], ['turmas_sugeridas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turma_sugerida_encontro', schema=None) as batch_op:
        batch_op.create_index('ix_encontro_turma_data', ['turma_sugerida_id', 'data'], unique=False)
        batch_op.create_index(batch_op.f('ix_turma_sugerida_encontro_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_turma_sugerida_encontro_turma_sugerida_id'), ['turma_sugerida_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma_sugerida_encontro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turma_sugerida_encontro_turma_sugerida_id'))
        batch_op.drop_index(batch_op.f('ix_turma_sugerida_encontro_data'))
        batch_op.drop_index('ix_encontro_turma_data')

    op.drop_table('turma_sugerida_encontro')
    with op.batch_alter_table('turmas_sugeridas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turmas_sugeridas_tipologia_id'))
        batch_op.drop_index(batch_op.f('ix_turmas_sugeridas_simulacao_id'))
        batch_op.drop_index(batch_op.f('ix_turmas_sugeridas_projeto_id'))
        batch_op.drop_index(batch_op.f('ix_turmas_sugeridas_instrutor_id'))
        batch_op.drop_index('ix_turma_sugerida_sim_tipologia')
        batch_op.drop_index('ix_turma_sugerida_sim_inicio')

    op.drop_table('turmas_sugeridas')
    with op.batch_alter_table('turmas_em_andamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turmas_em_andamento_tipologia_id'))
        batch_op.drop_index(batch_op.f('ix_turmas_em_andamento_projeto_id'))
        batch_op.drop_index(batch_op.f('ix_turmas_em_andamento_instrutor_id'))
        batch_op.drop_index('ix_turma_andamento_periodo')

    op.drop_table('turmas_em_andamento')
    with op.batch_alter_table('snapshot_capacidade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_capacidade_simulacao_id'))
        batch_op.drop_index(batch_op.f('ix_snapshot_capacidade_instrutor_id'))

    op.drop_table('snapshot_capacidade')
    with op.batch_alter_table('resultado_kpis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resultado_kpis_simulacao_id'))

    op.drop_table('resultado_kpis')
    with op.batch_alter_table('instrutor_turno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrutor_turno_instrutor_id'))

    op.drop_table('instrutor_turno')
    with op.batch_alter_table('instrutor_tipologia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrutor_tipologia_tipologia_id'))
        batch_op.drop_index(batch_op.f('ix_instrutor_tipologia_instrutor_id'))

    op.drop_table('instrutor_tipologia')
    with op.batch_alter_table('instrutor_dia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrutor_dia_instrutor_id'))

    op.drop_table('instrutor_dia')
    with op.batch_alter_table('simulacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulacoes_status'))
        batch_op.drop_index(batch_op.f('ix_simulacoes_cenario_id'))
        batch_op.drop_index('ix_simulacao_cenario_iniciado')

    op.drop_table('simulacoes')
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrutores_projeto_id'))
        batch_op.drop_index(batch_op.f('ix_instrutores_nome'))

    op.drop_table('instrutores')
    with op.batch_alter_table('datas_nao_letivas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datas_nao_letivas_projeto_id'))
        batch_op.drop_index('ix_data_nao_letiva_intervalo')

    op.drop_table('datas_nao_letivas')
    with op.batch_alter_table('cenario_projeto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cenario_projeto_projeto_id'))
        batch_op.drop_index(batch_op.f('ix_cenario_projeto_cenario_id'))

    op.drop_table('cenario_projeto')
    with op.batch_alter_table('tipologias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipologias_nome'))

    op.drop_table('tipologias')
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projetos_nome'))

    op.drop_table('projetos')
    op.drop_table('cenarios')
    # ### end Alembic commands ###
