"""adiciona snapshot de parametros na simulacao

Revision ID: d5c82375ef1c
Revises: b136564f2f5d
Create Date: 2026-08-05 20:37:55.991048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5c82375ef1c'
down_revision: Union[str, Sequence[str], None] = 'b136564f2f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parametros_json_path', sa.String(length=500), nullable=True, comment='Snapshot do arquivo de parâmetros usado nesta execução. Congelado no disparo — editar os pesos do cenário depois não altera este valor.'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulacoes', schema=None) as batch_op:
        batch_op.drop_column('parametros_json_path')

    # ### end Alembic commands ###
